apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sa-patcher.fullname" . }}
  labels:
    {{- include "sa-patcher.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resourceNames: ["default"]
    resources: ["serviceaccounts"]
    verbs: ["*"]