apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sa-patcher.serviceAccountName" . }}
  labels:
    {{- include "sa-patcher.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

